"""empty message

Revision ID: 271a95067e1a
Revises: 747a57aec108
Create Date: 2019-07-08 12:49:42.957325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271a95067e1a'
down_revision = '747a57aec108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('score', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'score')
    # ### end Alembic commands ###
