"""empty message

Revision ID: 30f898fe4060
Revises: d308fc72dad1
Create Date: 2019-06-08 02:17:11.307399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f898fe4060'
down_revision = 'd308fc72dad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('date_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'date_updated')
    # ### end Alembic commands ###
