"""empty message

Revision ID: 747a57aec108
Revises: b2d3543e204f
Create Date: 2019-07-08 11:40:33.374932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747a57aec108'
down_revision = 'b2d3543e204f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'rating')
    op.drop_column('recipes', 'comment_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('comment_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('rating', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
