"""empty message

Revision ID: 8b43754bc0cb
Revises: 271a95067e1a
Create Date: 2019-07-08 15:16:37.499903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b43754bc0cb'
down_revision = '271a95067e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('score', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
