"""empty message

Revision ID: a2c77cd0f146
Revises: 856175d166b2
Create Date: 2019-06-14 17:18:18.829038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2c77cd0f146'
down_revision = '856175d166b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'categories', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'created_by')
    # ### end Alembic commands ###
