"""empty message

Revision ID: b2d3543e204f
Revises: cb07151dc350
Create Date: 2019-07-07 19:44:15.189345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2d3543e204f'
down_revision = 'cb07151dc350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('comment_text', sa.String(length=100), nullable=True))
    op.add_column('recipes', sa.Column('rating', sa.String(length=100), nullable=True))
    op.alter_column('recipes', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('recipes', 'rating')
    op.drop_column('recipes', 'comment_text')
    # ### end Alembic commands ###
